/* ===================================================================
   build-data.js — one-shot converter from the raw Phase 1C CSV into
   the JavaScript data files the app loads.

   Produces:
     data-private.js   — full dataset, every email/phone intact (GITIGNORED)
     data.js           — public dataset with personal contact emails/phones masked
     data/leads_masked.csv — masked CSV, safe to commit

   Run: node build-data.js
   =================================================================== */

const fs = require('fs');
const path = require('path');

const SRC = path.join('data', 'Phase_1C_Contacts_Signals_Scoring.csv');

/* ---- Minimal RFC-4180 CSV parser (handles quotes, commas, CRLF) ---- */
function parseCSV(text) {
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;

  for (let i = 0; i < text.length; i++) {
    const c = text[i];

    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } // escaped quote
        else inQuotes = false;
      } else {
        field += c;
      }
    } else {
      if (c === '"') {
        inQuotes = true;
      } else if (c === ',') {
        row.push(field); field = '';
      } else if (c === '\r') {
        // swallow; the \n that follows ends the row
      } else if (c === '\n') {
        row.push(field); field = '';
        rows.push(row); row = [];
      } else {
        field += c;
      }
    }
  }
  // trailing field/row if file doesn't end in newline
  if (field !== '' || row.length > 0) { row.push(field); rows.push(row); }
  return rows;
}

/* ---- snake_case CSV column -> camelCase object key ---- */
function toCamel(s) {
  return s.replace(/_([a-z0-9])/g, (_, ch) => ch.toUpperCase());
}

/* ---- Normalize the raw outreach_status to a display pipeline stage ---- */
const STAGE_MAP = {
  not_contacted: 'Not Contacted',
  reached_out: 'Reached Out',
  followed_up: 'Followed Up',
  booked: 'Booked',
  declined: 'Declined',
  // "dead" leads (distressed/receivership/vacant buildings we're not pursuing)
  // fold into the terminal negative stage so the pipeline stays at 5 columns.
  dead: 'Declined',
};
function normalizeStage(raw) {
  const key = String(raw || '').trim().toLowerCase();
  if (STAGE_MAP[key]) return STAGE_MAP[key];
  // Unknown -> title case, never a raw code
  if (!key) return 'Not Contacted';
  return key.replace(/_/g, ' ').replace(/\b\w/g, (m) => m.toUpperCase());
}

/* ---- Personal fields to mask in the public outputs ---- */
const MASK_KEYS = ['txEmail', 'txPhone', 'gmEmail', 'gmPhone', 'opsEmail', 'opsPhone'];
const MASK_CSV_COLS = ['tx_email', 'tx_phone', 'gm_email', 'gm_phone', 'ops_email', 'ops_phone'];

/* =================================================================== */

const raw = fs.readFileSync(SRC, 'utf8');
const rows = parseCSV(raw);
const header = rows[0];
const dataRows = rows.slice(1).filter((r) => r.some((c) => c.trim() !== ''));

console.log(`Columns: ${header.length}  |  Data rows: ${dataRows.length}`);

// Build full building objects (camelCase keys, all columns retained).
const buildings = dataRows.map((cells) => {
  const obj = {};
  header.forEach((col, idx) => {
    obj[toCamel(col)] = (cells[idx] !== undefined ? cells[idx] : '').trim();
  });
  // Stable id from the slug; normalized pipeline stage for app logic.
  obj.id = obj.buildingId;
  obj.outreachStatus = normalizeStage(obj.outreachStatus);
  return obj;
});

// Numeric coercion for the fields the UI does math on.
buildings.forEach((b) => {
  b.numFloorsNum = parseInt(String(b.numFloors).replace(/[^0-9]/g, ''), 10) || 0;
  b.rentableSfNum = parseInt(String(b.rentableSf).replace(/[^0-9]/g, ''), 10) || 0;
  b.estDaytimePopulationNum = parseInt(String(b.estDaytimePopulation).replace(/[^0-9]/g, ''), 10) || 0;
  b.leadScoreNum = parseInt(String(b.leadScore).replace(/[^0-9]/g, ''), 10) || 0;
  b.softCriteriaCountNum = parseInt(String(b.softCriteriaCount).replace(/[^0-9]/g, ''), 10) || 0;
});

// Masked copy for the public data file.
function maskedCopy(b) {
  const copy = { ...b };
  MASK_KEYS.forEach((k) => { if (k in copy) copy[k] = ''; });
  return copy;
}
const maskedBuildings = buildings.map(maskedCopy);

/* ---- Write data-private.js (FULL) ---- */
const banner = '/* AUTO-GENERATED by build-data.js — do not edit by hand. */\n';
fs.writeFileSync(
  'data-private.js',
  banner +
  '/* PRIVATE: contains real emails/phones. This file is gitignored. */\n' +
  'window.POPUP_BAGELS_DATA = ' + JSON.stringify(buildings, null, 2) + ';\n'
);

/* ---- Write data.js (MASKED, public) ---- */
fs.writeFileSync(
  'data.js',
  banner +
  '/* PUBLIC: personal contact emails/phones are masked. Safe to commit. */\n' +
  'window.POPUP_BAGELS_DATA = ' + JSON.stringify(maskedBuildings, null, 2) + ';\n'
);

/* ---- Write data/leads_masked.csv (MASKED) ---- */
const maskIdx = header.map((col) => MASK_CSV_COLS.includes(col));
function csvCell(v) {
  const s = String(v == null ? '' : v);
  return /[",\r\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
}
const outLines = [header.map(csvCell).join(',')];
dataRows.forEach((cells) => {
  const masked = header.map((_, idx) => (maskIdx[idx] ? '' : (cells[idx] ?? '')));
  outLines.push(masked.map(csvCell).join(','));
});
fs.writeFileSync(path.join('data', 'leads_masked.csv'), outLines.join('\r\n') + '\r\n');

console.log('Wrote data-private.js, data.js, data/leads_masked.csv');
console.log(`Masked ${MASK_KEYS.length} personal fields per building in public outputs.`);
